<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <PublishSingleFile>true</PublishSingleFile>
    <PublishTrimmed>false</PublishTrimmed>
    <AssemblyName>ftu</AssemblyName>
    <Title>File Transfer Utility</Title>
    <Description>A data driven file transfer utility which copies or moves files from one or multiple source directories to the destination directory based on the `delimited file` (comma / tab / pipe files) or directory `search pattern` (Example: *.png, *.*).</Description>
    <Product>ftu</Product>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" /> 
    <PackageReference Include="Microsoft.Extensions.Configuration" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Microsoft.Extensions.Logging" />
    <PackageReference Include="Serilog.Extensions" />
    <PackageReference Include="Serilog.Settings.Configuration" />
    <PackageReference Include="Serilog.Sinks.Console" />
    <PackageReference Include="Serilog.Sinks.File" />
    <PackageReference Include="SonarAnalyzer.CSharp">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="System.CommandLine" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Commands/" />
    <Folder Include="Configurations/" />
    <Folder Include="Constants/" />
    <Folder Include="Extensions/" />
    <Folder Include="Handlers/" />
    <Folder Include="Mappers/" />
    <Folder Include="Models/" />
    <Folder Include="Options/" />
    <Folder Include="Writer/" />
 </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Sphere.FileTransfer.Models/Sphere.FileTransfer.Models.csproj" />
    <ProjectReference Include="../Sphere.FileTransfer.Services/Sphere.FileTransfer.Services.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="ftu.appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
