<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <InvariantGlobalization>true</InvariantGlobalization>
    <AssemblyName>ftu.Services</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Sphere.FileTransfer.Models/Sphere.FileTransfer.Models.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Models/" />
    <Folder Include="Readers/" />
    <Folder Include="Validators/" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.3" />
  </ItemGroup>

</Project>
