<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Sphere.FileTransfer.Models/Sphere.FileTransfer.Models.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Models/" />
    <Folder Include="Readers/" />
  </ItemGroup>

</Project>
